# Generated by Django 5.0.2 on 2024-03-16 17:02

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rodic',
            options={'verbose_name_plural': 'Rodiče'},
        ),
        migrations.AlterField(
            model_name='rodic',
            name='telefon',
            field=phone_field.models.PhoneField(max_length=30),
        ),
    ]
