# Generated by Django 5.0.2 on 2024-03-16 17:06

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0002_alter_rodic_options_alter_rodic_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodic',
            name='telefon',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
