# Generated by Django 5.0.2 on 2024-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0003_alter_rodic_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodic',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
