# Generated by Django 5.0.2 on 2024-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0006_alter_rodic_bydliste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30)),
                ('prijmeni', models.CharField(max_length=30)),
                ('datum_narozeni', models.DateField()),
                ('alergie', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Děti',
            },
        ),
        migrations.AddField(
            model_name='rodic',
            name='dite',
            field=models.ManyToManyField(to='rezervacni_system.dite'),
        ),
    ]
