# Generated by Django 5.0.2 on 2024-03-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0007_dite_rodic_dite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodic',
            name='dite',
        ),
        migrations.AddField(
            model_name='dite',
            name='rodice',
            field=models.ManyToManyField(to='rezervacni_system.rodic'),
        ),
        migrations.AddField(
            model_name='rodic',
            name='poznamka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SportovniAkce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('datum', models.DateField()),
                ('prihlasene_deti', models.ManyToManyField(to='rezervacni_system.dite')),
            ],
        ),
    ]
