# Generated by Django 5.0.2 on 2024-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0008_remove_rodic_dite_dite_rodice_rodic_poznamka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dite',
            name='datum_narozeni',
        ),
        migrations.AddField(
            model_name='dite',
            name='vek',
            field=models.IntegerField(null=True),
        ),
    ]
