# Generated by Django 5.0.2 on 2024-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0009_remove_dite_datum_narozeni_dite_vek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportovniakce',
            old_name='jmeno',
            new_name='nazev',
        ),
        migrations.AlterField(
            model_name='sportovniakce',
            name='prihlasene_deti',
            field=models.ManyToManyField(blank=True, to='rezervacni_system.dite'),
        ),
    ]
