# Generated by Django 5.0.2 on 2024-03-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0010_rename_jmeno_sportovniakce_nazev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dite',
            name='akce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervacni_system.sportovniakce'),
        ),
    ]
