# Generated by Django 5.0.2 on 2024-03-19 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0011_dite_akce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dite',
            name='akce',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervacni_system.sportovniakce'),
        ),
    ]
