# Generated by Django 5.0.2 on 2024-03-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0013_remove_dite_akce_dite_akce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportovniakce',
            name='prihlasene_deti',
        ),
    ]
