# Generated by Django 5.0.2 on 2024-03-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0014_remove_sportovniakce_prihlasene_deti'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportovniakce',
            name='prihlasene_deti',
            field=models.ManyToManyField(blank=True, to='rezervacni_system.dite'),
        ),
    ]
