# Generated by Django 5.0.2 on 2024-03-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0017_remove_sportovniakce_prihlasene_deti_rodic_dite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dite',
            name='rodice',
        ),
    ]
