# Generated by Django 5.0.2 on 2024-03-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0018_remove_dite_rodice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dite',
            old_name='jmeno',
            new_name='dite_jmeno',
        ),
        migrations.RenameField(
            model_name='dite',
            old_name='prijmeni',
            new_name='dite_prijmeni',
        ),
        migrations.RenameField(
            model_name='rodic',
            old_name='jmeno',
            new_name='rodic_jmeno',
        ),
        migrations.RenameField(
            model_name='rodic',
            old_name='prijmeni',
            new_name='rodic_prijmeni',
        ),
    ]
