# Generated by Django 5.0.2 on 2024-03-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0019_rename_jmeno_dite_dite_jmeno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportovniakce',
            name='seznam_deti',
            field=models.ManyToManyField(blank=True, to='rezervacni_system.dite'),
        ),
    ]
