# Generated by Django 5.0.2 on 2024-03-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0020_sportovniakce_seznam_deti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodic',
            name='dite',
        ),
    ]
