# Generated by Django 5.0.2 on 2024-03-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0021_remove_rodic_dite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportovniakce',
            options={'verbose_name_plural': 'Sportovní Akce'},
        ),
        migrations.RemoveField(
            model_name='sportovniakce',
            name='seznam_deti',
        ),
        migrations.RemoveField(
            model_name='dite',
            name='akce',
        ),
        migrations.AddField(
            model_name='dite',
            name='akce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervacni_system.sportovniakce'),
        ),
    ]
