# Generated by Django 5.0.2 on 2024-03-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0022_alter_sportovniakce_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dite',
            name='akce',
        ),
        migrations.AddField(
            model_name='dite',
            name='rodice',
            field=models.ManyToManyField(to='rezervacni_system.rodic'),
        ),
        migrations.AddField(
            model_name='sportovniakce',
            name='seznam_deti',
            field=models.ManyToManyField(blank=True, to='rezervacni_system.dite'),
        ),
    ]
