# Generated by Django 5.0.2 on 2024-03-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0023_remove_dite_akce_dite_rodice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportovniakce',
            name='seznam_deti',
            field=models.ManyToManyField(to='rezervacni_system.dite'),
        ),
    ]
