# Generated by Django 5.0.2 on 2024-03-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0024_alter_sportovniakce_seznam_deti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportovniakce',
            name='seznam_deti',
            field=models.ManyToManyField(blank=True, to='rezervacni_system.dite'),
        ),
    ]
