# Generated by Django 5.0.2 on 2024-03-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0025_alter_sportovniakce_seznam_deti'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodic',
            name='dite_rodic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervacni_system.dite'),
        ),
    ]
