# Generated by Django 5.0.2 on 2024-03-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0026_rodic_dite_rodic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dite',
            name='rodice',
        ),
        migrations.RemoveField(
            model_name='rodic',
            name='dite_rodic',
        ),
        migrations.AddField(
            model_name='dite',
            name='rodic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervacni_system.rodic'),
        ),
    ]
