# Generated by Django 5.0.2 on 2024-03-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0027_remove_dite_rodice_remove_rodic_dite_rodic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dite',
            name='akce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervacni_system.sportovniakce'),
        ),
    ]
