# Generated by Django 5.0.2 on 2024-03-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0028_dite_akce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dite',
            name='akce',
        ),
    ]
