# Generated by Django 5.0.2 on 2024-03-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0029_remove_dite_akce'),
    ]

    operations = [
        migrations.AddField(
            model_name='dite',
            name='akce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervacni_system.sportovniakce'),
        ),
    ]
