# Generated by Django 5.0.2 on 2024-03-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0030_dite_akce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dite',
            name='alergie',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='dite',
            name='poznamka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
