# Generated by Django 5.0.2 on 2024-03-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0031_alter_dite_alergie_alter_dite_poznamka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportovniakce',
            old_name='datum',
            new_name='termin',
        ),
    ]
