# Generated by Django 5.0.2 on 2024-03-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervacni_system', '0032_rename_datum_sportovniakce_termin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportovniakce',
            name='termin',
        ),
        migrations.AddField(
            model_name='sportovniakce',
            name='termin_do',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sportovniakce',
            name='termin_od',
            field=models.DateField(null=True),
        ),
    ]
